apiVersion: v1
kind: Service
metadata:
  name: todo-service
spec:
  selector:
    app: todo
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 3000
      nodePort: 30080 